[package]
name = "ioc_macros"
version = "0.7.0"
authors = ["Felix KÃ¶pge <fkoep@mailbox.org>"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.11", features = ["full"] }
quote = "0.3"
